# Generated by Django 6.0.2 on 2026-03-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_review_rating_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
